# Generated by Django 5.2.9 on 2026-04-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskms", "0002_attachment_comment_subtask_tag_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "To Do"),
                    ("in_progress", "In Progress"),
                    ("review", "Under Review"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
